- name: create namespace
  hosts: localhost
  connection: local
  tasks:
    - name: create namespace
      k8s:
        name: my-app
        api_version: v1
        kind: namespace
        state: present
    - name: Deploy python app
      k8s:
        src: /K8s-Deployment/app-deploy.yaml
        state: present
        namespace: my-app
